---
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: reproducer
  namespace: fleet-local
spec:
  repo: https://github.com/p-se/fleet-test-data
  branch: SURE-9137
  paths:
  - reproducer

