#!/usr/bin/env bash

kubectl patch clusters.fleet.cattle.io -n fleet-default downstream \
    --type='json' -p='[{"op": "replace", "path": "/metadata/labels/foo", "value": "one"}]'
kubectl delete -f gitrepo.yaml
kubectl apply -f gitrepo.yaml
