apiVersion: apps/v1
kind: Deployment
metadata:
  name: sure-7399-c
  namespace: default
  labels:
    app: sure-7399-c
spec:
  selector:
    matchLabels:
      app: sure-7399-c
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sure-7399-c
    spec:
      containers:
        - name: sure-7399-c
          image: nginx:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
      restartPolicy: Always
